//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace calendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class miappcal_sch
    {
        public int cal_id { get; set; }
        public string @event { get; set; }
        public string event_desc { get; set; }
        public Nullable<System.DateTime> bgn_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string cal_type { get; set; }
        public Nullable<bool> is_important { get; set; }
    }
}
